keybindings = [
  { key = { F = 1 }, action = { SelectTab = 0 } },
  { key = { F = 2 }, action = { SelectTab = 1 } },
  { key = { F = 3 }, action = { SelectTab = 2 } },
  { key = { F = 4 }, action = { SelectTab = 3 } },
  { key = { F = 5 }, action = { SelectTab = 4 } },
]

[[names.overrides]]
types = ["endpoint", "device"]
property = "device:device.nick"
value = "sof-hda-dsp"
templates = ["{node:node.nick}", "{node:node.description}", "{device:device.description}"]
